### ISSUE TITLE
don't have tha api key?

### ISSUE THREAD

**Issue by mauorycy22** [rhettlunn/is-odd-ai#10]

**Comment by mauorycy22** [comment]
hi the token seems to have been not put in the code and as such the program does not work and i wanted to implement it in my program.

Is it a known issue? Will it be fixed? Cann you give me the api?

**Comment by mauorycy22** [comment]
i found the key in another repo, thank you!

**Comment by xorraxraxret** [comment]
> i found the key in another repo, thank you!

i heard you have an api key , can you post it her e?
